#!/bin/bash

vms="$(xe vm-list | grep "name-label" | grep -v "Control domain" | tr -s " " | cut -d " " -f 5)"

# Incluir no /etc/fstab uma entrada para o diretorio de backup
# Alterar de acordo com a sua configuração.
dirBack=/mnt/backup

mount $dirBack

#IFS="
#"

for vm in $(echo $vms)
do

    time=$(date --date "now" +%d_%m_%y_%H_%M)

    snapName=$vm-bk-$time

    ID=$(xe vm-snapshot vm=$vm new-name-label=$snapName &&
            {
            logger -t "XenBackup" -s "$vm - OK Passo 1"
            }||{
            logger -t "XenBackup" -s "$vm - ERR Passo 1"
            umount $dirBack
            xe vm-uninstall vm=$snapName force=true
            echo 1
            })


    if [ "$ID" == "1" ]
    then
            exit 1
    fi

    xe template-param-set is-a-template=false uuid=$ID &&
        {
        logger -t "XenBackup" -s "$vm - OK Passo 2"
        }||{
        logger -t "XenBackup" -s "$vm - ERR Passo 2"
	umount $dirBack
	xe vm-uninstall vm=$snapName force=true
        exit 2
        }

    xe vm-export vm=$snapName  filename=$dirBack/$snapName
        {
        logger -t "XenBackup" -s "$vm - OK Passo 3"
        }||{
        logger -t "XenBackup" -s "$vm - ERR Passo 3"
	umount $dirBack
	xe vm-uninstall vm=$snapName force=true
        exit 3
        }

    xe vm-uninstall vm=$snapName force=true
        {
        logger -t "XenBackup" -s "$vm - OK Passo 4"
        }||{
        logger -t "XenBackup" -s "$vm - ERR Passo 4"
	umount $dirBack
        exit 4
        }

gzip $dirBack/$snapName
       {
       logger -t "XenBackup" -s "$vm - OK Passo 5"
       }||{
       logger -t "XenBackup" -s "$vm - ERR Passo 5"
       umount $dirBack
       exit 5
       }
done
umount $dirBack
exit 0
